#!/bin/bash

################################
# UNIXycle - A UNIX recycle bin
################################
# Author: Elliott Steer
# Docs: https://github.com/essteer/unixycle/blob/main/README.md
#
# `restore` retrieves files from a recyclebin directory in a 
# user's $HOME that were previously recycled via the `recycle`
# script, and recreates parent directories that no longer exist.
#
# File usage:
# "$ bash restore oops.txt_64135"
#
# Data for recycled files is stored in $HOME/.restore.info.
# See the accompanying `recycle` script for details.
#################################

recyclebin_abs_path="$HOME/recyclebin"
restore_info_abs_path="$HOME/.restore.info"

if [ "$#" -eq 0 ] ; then
    echo "restore: missing operand"
    exit 1  # exit if no args provided
fi

function show_help() {
    echo "Usage: bash restore [FILE]"
    echo
    echo "Options:"
    echo "  -h    Display help"
}

OPTIND=1
while getopts ":h" opt
do
    case $opt in
        h|H)
            show_help
            exit 0
            ;;
    esac
done

recycle_state_name="$(basename "$1")"
target_abs_path_in_recyclebin="${recyclebin_abs_path}/${recycle_state_name}"

if ! [ -e "$target_abs_path_in_recyclebin" ] ; then
    echo "cannot restore '$1': no such file"
    exit 2  # exit if file does not exist
fi

data_in_restore_info=$(cat "$restore_info_abs_path" | grep "$recycle_state_name")
target_original_abs_path=$(echo -n "$data_in_restore_info" | cut -d: -f2)

if [ -e "$target_original_abs_path" ] ; then
    echo "$target_original_abs_path already exists"
    read -p "Do you want to overwrite? y/n " overwriteDecision

    if [ "$overwriteDecision" != "y" ] && [ "$overwriteDecision" != "Y" ] ; then
        exit 3  # user declined file overwrite 
    fi
fi

# create missing parent dirs for target file original location
target_original_dir=$(dirname "$target_original_abs_path")
mkdir -p "$target_original_dir"
# restore target file from recyclebin to original location
mv "$target_abs_path_in_recyclebin" "$target_original_abs_path"
# delete data on target file from .restore.info
grep -v "$data_in_restore_info" "$restore_info_abs_path" > tmp
mv tmp "$restore_info_abs_path"  # overwrite .restore.info with tmp file from grep -v

exit 0
