#!/bin/bash

echo "01 test with no args: "
bash recycle
echo ""

echo "02 test with non-existing file: "
bash recycle relgcnqrqrhgb
echo ""

echo "03 test with dir name: "
mkdir ephemeral_dir
bash recycle ephemeral_dir
rm -rf ephemeral_dir
echo ""

echo "04 test with valid file: "
touch ephemeral_file
bash recycle ephemeral_file
echo ""

echo "05 test recycle via direct path: recycle"
bash recycle recycle
echo ""

echo "06 test recycle via rel path: ./recycle"
bash recycle ./recycle
echo ""

echo "07 test recycle via abs path: abs/path/recycle"
bash recycle "$(realpath recycle)"
echo ""

echo "tests complete"
echo ""
